### ISSUE TITLE
FE: api 요청 시나리오

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#108]
## 📝 개요
- 베이스url, 토큰재발급등 api 요청을 더 편하게하는 시나리오 작성

## ✔️ To-Do
- [ ] 베이스 url 설정
- [ ] 요청에 자동으로 엑세스토큰 받아 보내기
- [ ] 엑세스토큰 권한에러시 자동으로 리프레시토큰 요청 후 보내기

## 👀 ETC
-
