### ISSUE TITLE
BE: OAuth 로그인 개발

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#14]
## 📝 개요
- Google, Naver, Kakao OAuth 로그인 개발

## ✔️ To-Do
- [x] auth directory 생성
- [x] auth strategy 생성
- [x] User Entity 생성
- [x] 받은 User data DB에 저장

## 👀 ETC
- 참고자료 등 기타 내용 작성
