### ISSUE TITLE
FE: fix switch storybook

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#146]
## 📝 개요
- Switch에 대한 storybook
- onChange, name, id등의 불필요한 옵션이 표시되고 있음
- checked 옵션이 동작하지 않음
- size 제어는 옵션으로 제공되고 있음과 동시에 컴포넌트 하위 프리셋 목록에도 동일하게 표시됨. (불필요한 중복 옵션을 제거할 필요가 있음)

## ✔️ To-Do
- [ ] onChange, name, id등의 불필요한 옵션을 삭제
- [ ] checked 옵션이 동작하지 않는 문제 수정
- [ ] size 관련 불필요한 중복 옵션 제거

## 👀 ETC
![image](https://github.com/user-attachments/assets/b009134e-37d1-453d-a7b5-297edc5ccf72)
![image](https://github.com/user-attachments/assets/d7385f44-7500-42d5-b0df-b9b520ebcd33)

**Comment by easyandones** [comment]
moving to #149
