### ISSUE TITLE
FE: session detail page

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#167]
## 📝 개요
- 세션 상세보기 및 수정 페이지

## ✔️ To-Do
- [ ] 세션 제목 수정
- [ ] 세션 파일추가 버튼(기능구현x)
- [ ] 세션 시작 버튼(기능구현x)

## 👀 ETC
- 역할에 따라 달라지는 ui
