### ISSUE TITLE
BE: /file/:fileId APIs 개발

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#168]
## 📝 개요
- 파일 정보 가져오기
- 파일 정보 바꾸기
- 파일 삭제하기 

## ✔️ To-Do
- [ ] GET /file/:fileId
- [ ] PATCH /file/:fileId
- [ ] DELETE /file/:fileId

## 👀 ETC
- 참고자료 등 기타 내용 작성
