### ISSUE TITLE
BE: /auth/logout 구현

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#170]
## 📝 개요
- 로그아웃 구현하기

## ✔️ To-Do
- [ ] refresh token 받아서 userId 얻기
- [ ] userId 가지고 DB에서 refreshToken 삭제
- [ ] 클라이언트 쿠키 삭제

## 👀 ETC
- 참고자료 등 기타 내용 작성
