### ISSUE TITLE
FE: session rewrite page

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#185]
## 📝 개요
- 세션 정보 수정 가능한 페이지

## ✔️ To-Do
- [ ] 세션 정보 수정
- [ ] 파일 업로드 모달
- [ ] 내 컴퓨터 파일 업로드
- [ ] 드라이브 파일 업로드

## 👀 ETC
- 세션 업로드도 그대로 할 수 있음
- 추가적인 로직 구현 필요
  - 선택한 파일 데이터 핸들링
  - 기존 세션 정보 서버로부터 받아오기 후 default value로 set
