### ISSUE TITLE
FE: 라우팅 구조 변경

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#204]
## 📝 개요
- 문서에 title tag가 없고 meta태그를 제어할 수 없음
- 이를위해 예외적으로 root layout은 server컴포넌트를 사용해야함
- 상태로 레아이웃을 제어하기보단 ghost route ((route)와 같은 괄호 디렉토리)를 사용하면 레이아웃을 더 쉽게 관리할 수 있음

## ✔️ To-Do
- [ ] 대쉬보드,세션,파일 등의 사이드바가 필요한 레이아웃을 고스트 라우트 + layout.tsx 로 이용해 관리
- [ ] root layout에 title 및 description 추가
- [ ] root layout server-component화

## 👀 ETC
-
