### ISSUE TITLE
FE: session patch & create form 권장사항 맞게 수정

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#243]
## 📝 개요
- jotai를 사용하는게 아닌 new FormData(ref)형식

## ✔️ To-Do
- [ ] session/create handleSubmit 로직 수정
- [ ] session/detail (host) handleSubmit 로직 수정
- [ ] drivefileselect jotai 삭제 및 input 활용

## 👀 ETC
- https://github.com/Uni-class/catch-up-repo/discussions/242
- https://github.com/Uni-class/catch-up-repo/pull/221
- FORM data 형식 서버와 합의 필요
