### ISSUE TITLE
FE: view/[session]

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#244]
## 📝 개요
- 세션 참여 페이지 제작

## ✔️ To-Do
- [ ] [react-pdf](https://www.npmjs.com/package/react-pdf) 설치
- [ ] public 임시 pdf 파일 연동
- [ ] 방향키를 통한 페이지네이션 로직

## 👀 ETC
-
