### ISSUE TITLE
BE: Socket server Develop

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#311]
## 📝 개요
- 소켓 서버 Sub, emit 구성

## ✔️ To-Do
- [ ] Host to Server
- [ ] Server to Participant
- [ ] Data save in DB or S3

## 👀 ETC
- 참고자료 등 기타 내용 작성
