### ISSUE TITLE
FE: 기획심의용 레이아웃 변경

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#320]
## 📝 개요
- 레이아웃 변경
  - 세션 상세
  - 사이드바
  - 세션 생성
  - 세션 접속

## ✔️ To-Do
- [ ] 세션 상세보기 레이아웃 변경
- [ ] 사이드바 중복되는 버튼 삭제 및 유튜브 로고 삭제
- [ ] 프로필 이미지가 1:1비율이 아닌 점 해결
- [ ] 폼 중앙 정렬

## 👀 ETC
- 폼 레이아웃은 위시켓인가 어디 외주사이트 레퍼런스
