### ISSUE TITLE
TOT: push할때 어떤 스크립트를 자동 실행한 커밋을 날린 뒤 push하기

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#369]
### [Husky](https://www.npmjs.com/package/husky)를 사용하면 커밋을 push하기전 작동할 동작을 정의 가능
- 이걸로 푸시 하기 전 특정 커밋을 자동화하면 좋지 않을까?
- pre-push hook을 사용하면 될 것이다
## ✔️ To-Do
- [ ] 린드,프리티어 등 동작
- [ ] panda css codegen 동작
- [ ] 이외 동작할 것들...

## 👀 ETC
- 굳이 지금할 필욘 없고요?
