### ISSUE TITLE
FE: socket-event 배치 처리

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#370]
## 📝 개요
- 소켓 이벤트를 10~20fps로 배치 처리

## ✔️ To-Do
- [ ] 배치 데이터 구조 생성( {RecordId:Queue(["event",msgBody])}
- [ ] 배치 데이터를 이용해 효율적으로 데이터 압축
- [ ] 특정 시간을 트리거해 큐를 비움, 큐가 비워졌다면 key 삭제
## 👀 ETC
-
