### ISSUE TITLE
BE: Redis adapter -> socket server에 연결하기

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#371]
## 📝 개요
- scale out을 위해 Redis를 두어 pub/sub 으로 메세지 읽어오게 설정

## ✔️ To-Do
- [ ] ec2에 redis 올리기
- [ ] 라이브러리 설치 (redis, redis-adapter) 
- [ ] 연결
- [ ] 데이터 받아지나 확인

## 👀 ETC
- 참고자료 등 기타 내용 작성
