### ISSUE TITLE
BE: 소켓서버 유저 데이터 개선

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#395]
## 📝 개요
- 방을 관리하고 파악하는데 많은 노력이 듬
- `private clients: Set<Socket> = new Set();`는 거의 쓰이지 않음
- 유저와 소켓id를 관리하는 자료구조가 현재 `clientUserId: { [key: string]: number } = {};`밖에 없음
- userId와 socketId를 일관적으로 관리해 관리 비용을 줄이는 법이 존재함

## ✔️ To-Do
- [ ] 1대1매핑 자료구조 사용 및 방은 userId와 socketId 둘중하나를 사용하면 간단한 서버 구축이 가능

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 양방향맵 사용
- https://www.npmjs.com/package/relation-map 해당 라이브러리 사용허세요
### 호스트 페이지 분포
- `pdfPageView = {roomId:new OneToManyMap<number,?>()}` ?엔 userId든 client.id든 편한 것 사용, 개인적으로 userId가 중복을 피할 수 있어 추천
- 유저는 그냥 현재 페이지만 보내주면 됨
- 호스트에게만 emit하기
### 참여자가 호스트 페이지 보기
- 그냥 이벤트 따로 만들어서 호스트 페이지 오고가게만 하면 됨
### connect
- `const userMap = new BiMap<string,number>()` clinent.id와 UserId매핑
- 만약 userId에 할당된 client id가 already exist라면 새 client id 갈아끼우면 안정적일듯
