### ISSUE TITLE
FE: 페이지 정보 공윺

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#407]
## 📝 개요
- 호스트 페이지 정보를 참여자가 알 수 있게한다.
- 임시적으로 글자만 보여주는 UI를 사용한다.

## ✔️ To-Do
- [ ] 이벤트 핸들러 제작

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
