### ISSUE TITLE
FE: pdf 페이지 미리보기 뷰

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#417]
## 📝 개요
- 좌측에 pdf 페이지 미리보기 뷰

## ✔️ To-Do
- [ ] 내가 보고 있는 페이지를 최상단에 위치
- [ ] 페이지 미리보기 우측 상단에 배지로 추가 정보(보고있는 페이지 등)
- [ ] 누르면 해당 페이지로 이동

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 기존 구글 pdf뷰어와같이 스크롤 조정하는 기능은 나중에
