### ISSUE TITLE
BE: 쿠키 도메인 항목 

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#421]
## 📝 개요
- 현재 왠진 모르겠는데 쿠키 도메인이 api.catchup.tools로 되어있음
- 그래서 쿠키가 socket server로 안 보내짐

## ✔️ To-Do
- [ ] 도메인 설정 만지기

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
