### ISSUE TITLE
FE: login redirect

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#425]
## 📝 개요
- 자세한 개요 작성

## ✔️ To-Do
- [ ] view/sessionID에서 미로그인 유저 리다이렉트
- [ ] /login에서 로그인유저 리다이렉트

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
