### ISSUE TITLE
FE: 사용자 정보 수정 검증

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#431]
## 📝 개요
- /settings의 폼 검증

## ✔️ To-Do
- [ ] 사용자 닉네임 유무
- [ ] 프로필사진? default가 있으므로...

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 약속이 있어서 세션 검증까지만
- 프로필 사진 상태가 변경이 안돼요 로직바꾼게 잇나?
```typescript

    //const isValidSrc = src && typeof src === "string" && src.trim() !== "";
    const [imgSrc, setImgSrc] = useState(defaultSrc);
    const [isError, setIsError] = useState(false);
    useEffect(()=>{
      const isValidSrc = src && typeof src === "string" && src.trim() !== "";
    setImgSrc(isValidSrc ? src : defaultSrc);
    },[src])
```
- 그냥 이거로 해결하면 됨, src가 바뀌어도 해당 컴포넌트가 감지 못해서 그랬음
