### ISSUE TITLE
FE&BE: 폼 검증 로직 상세화

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#433]
## 📝 개요
- 현재 폼 검증이 매우 간단해서 빠진 조건이 있는지 협의

## ✔️ To-Do
- [ ] 세션 생성(수정)시 제목에 대한 규칙
- [ ] 세션 생성(수정)시 파일에 대한 규칙
- [ ] 세션 코드에 대한 규칙
- [ ] 프로필 사진에 대한 규칙
- [ ] 닉네임에 대한 규칙

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- @1000chw 응답바랍니다

**Comment by 1000chw** [comment]
1. 제목은 글자수 제한 정도면 될 것 같음
2. 파일은 일단 1개 제한에 용량 제한은 안 둬야겠지?
3. 세션 코드는 자동생성이니까 넘어가고
4. 프로필 사진이랑 닉네임 규칙은 필요한가?

**Comment by nayounsang** [comment]
> 1. 제목은 글자수 제한 정도면 될 것 같음
> 2. 파일은 일단 1개 제한에 용량 제한은 안 둬야겠지?
> 3. 세션 코드는 자동생성이니까 넘어가고
> 4. 프로필 사진이랑 닉네임 규칙은 필요한가?

아직 검증로직 따로 없으면 수요일이나 금요일날
