### ISSUE TITLE
BE: user/sessions?role=host 일 때 세션 지우기

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#438]
## 📝 개요
- user sessions에서 가져와야 되는데 sessions에서 가져와서 버그남

## ✔️ To-Do
- [ ] 해당 코드 수정

## 예상 마감 기한
- [x] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
