### ISSUE TITLE
FE: remove tailwind and styled-component

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#45]
## 📝 개요
- 기존 tailwind와 styled component를 지웁니다

## ✔️ To-Do
- [ ] rmv package
- [ ] rmv tailwind config
- [ ] rmv styled-component provider
- [ ] rewrite styled-provider

## 👀 ETC
- 오류가 안나길 빌어야겠죠
- 다행히 styled-component로 작성한 스타일은 아직까진 하나밖에 없단 . 거
