### ISSUE TITLE
FE: 필기 데이터 저장 로직 개선

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#455]
## 📝 개요
- 필기 데이터의 저장 로직 개선 및 자동 저장 추가

## ✔️ To-Do
- [ ] 필기 데이터 관련 저장 로직 개선
- [ ] 필기 데이터 관련 자동 저장 로직 추가

## 예상 마감 기한
- [X] 우선순위가 낮아 고려 안함
