### ISSUE TITLE
BE: mongodb insert empty object

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#457]
## 📝 개요
- mongoDB에 빈 오브젝트가 들어가면 제거돼서 들어가짐

## ✔️ To-Do
- [ ] 안지워지게 세팅하기
- [ ] 어떻게 해야할지 모르겠음

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [x] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
