### ISSUE TITLE
FE: 야매 디자인 시스템

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#469]
## 📝 개요
- 일부 컴포넌트의 컬러 시스템을 현재에 맞게 수정

## ✔️ To-Do
- [ ] primary, secondary, tertiary props 설정

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
![image](https://github.com/user-attachments/assets/ea4c8d21-3415-49e7-b4f4-bb82243bf5c8)
여기에에있는 컬러
