### ISSUE TITLE
FE: Login page Color 수정

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#470]
## 📝 개요
- 디자인 바꾸는데 딜레이가 있으므로 color라도 수정해봅시다.
- 튀는 것만 제거해보자구요

## ✔️ To-Do
- [ ] 핑크,주황과같은 일부 강조컬러를 main(남색)컬러로 변환

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
-
