### ISSUE TITLE
FE: viewer design

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#475]
## 📝 개요
- 뷰어 디자인

## ✔️ To-Do
- [ ] 컨트롤바 수정
- [ ] 페이지 컨트럴 ui
- [ ] 미리보개 ui
## 예상 마감 기한
- [ ] 오늘
- [ ] 핫 픽스
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
