### ISSUE TITLE
FE: 세션 폼 제작

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#480]
## 📝 개요
- 디자인 시안 적용

## ✔️ To-Do
- [ ] 세션 생성 폼
- [ ] 세션 조인 폼
- [ ] 세션 정보보기 UI 생성 폼에 맞춰 수정

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
-
