### ISSUE TITLE
FE/BE: Host가 하나의 세션에서 여러 창 또는 탭으로 접속할 경우 처리

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#483]
## 📝 개요
- 여러 창/탭 접속을 차단하는 것은 일반적으로 좋지 않은 사용자 경험을 제공함.
- 여러 창/탭 접속을 허용하면서 host의 제어 또는 필기가 서로 원활히 동기화되도록 구현하는 방향이 좋을 것 같음.
- 이를 위해 host viewer에서도 host 이벤트가 수신되면 동기화 작업을 수행하도록 구현

방법 1.
host가 발생시키는 이벤트는 모두(현재 세션에 포함된 모두, 자신 포함)에게 broadcasting 되도록 websocket 서버를 구현
host는 이벤트를 서버로 전송할때 nonce 값을 담아서 보냄.
수신된 이벤트의 nonce값을 확인하고 현재 창/탭에서 발생시킨 이벤트라면 무시
수신된 이벤트의 nonce값이 처음보는 값이라면 (즉, host의 다른 창/탭에서 발생시킨 이벤트라면) 일반 participant과 동일하게 수신된 이벤트의 필기를 화면에 추가하거나 페이지를 이동

방법 2.
host가 발생시키는 이벤트를 그 이벤트를 전송한 websocket client만 제외한 나머지 모두에게 broadcasting 되도록 websocket 서버를 구현
client는 host view / participant view 상관없이 host 이벤트가 수신되면 현재 창에서 발생시킨 이벤트가 아니라는 것이 보장되기 때문에 수신된 이벤트의 필기를 화면에 추가하거나 페이지를 이동

## ✔️ To-Do
- [ ] 구현 방식 결정
- [ ] 구현

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [X] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

**Comment by nayounsang** [comment]
이거 이번 토스 슬래시에 shared worker 사용하는거랑 비슷한거 아닌가? 그냥 개빡센거같던데
한번 도전해보면 좋겠네

**Comment by easyandones** [comment]
> 이거 이번 토스 슬래시에 shared worker 사용하는거랑 비슷한거 아닌가? 그냥 개빡센거같던데 한번 도전해보면 좋겠네

복잡할건 없지 않을까? 그냥 저기 적힌 그대로만 해도 될거 같은데

**Comment by nayounsang** [comment]
> > 이거 이번 토스 슬래시에 shared worker 사용하는거랑 비슷한거 아닌가? 그냥 개빡센거같던데 한번 도전해보면 좋겠네
> 
> 복잡할건 없지 않을까? 그냥 저기 적힌 그대로만 해도 될거 같은데

저대로면 이미 지금도 되고있지않아? 현우랑얘기할때 딱히 차단은 안하도록 구현한걸로 알고있어서
안되고있으려나..한번봐야겠다
