### ISSUE TITLE
FE: table UI

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#487]
## 📝 개요
- 테이블 페이지 UI

## ✔️ To-Do
- [ ] 파일, 호스트세션, 참여자세션목록 페이지 테이블 UI

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
