### ISSUE TITLE
FE: Table Scroll

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#489]
## 📝 개요
- Table에서 overflow가 발생하여 scroll bar가 생성될때 Table Content 내부에 scroll bar가 생성되는 것이 아닌 Table View 전체에 scroll bar가 생성되어 scroll할 경우 Table Header 및 액션 버튼 등과 함께 Table View 전체가 scroll 되는 문제

## ✔️ To-Do
- [ ] Scroll Bar 생성 영역 수정

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [X] 우선순위가 낮아 고려 안함

**Comment by nayounsang** [comment]
이거 페이지네이션으로 기획하긴했는데 백엔드도 페이지넘버 주는걸로 알아

**Comment by nayounsang** [comment]
이참에 지원이가 페이지네이션 작업하는거어때? 페이지네이션 기능적용하면 스크롤 생길일이 거의 없으니까
https://www.figma.com/design/1avaJJ57g7eT2jJcxVtv60/Untitled?node-id=236-874&node-type=frame&t=DvuPU5SoGXuLqzkI-0

**Comment by easyandones** [comment]
> 이참에 지원이가 페이지네이션 작업하는거어때? 페이지네이션 기능적용하면 스크롤 생길일이 거의 없으니까 https://www.figma.com/design/1avaJJ57g7eT2jJcxVtv60/Untitled?node-id=236-874&node-type=frame&t=DvuPU5SoGXuLqzkI-0

오키오키
