### ISSUE TITLE
FE: 쿼리키 시스템화 및 캐싱

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#490]
## 📝 개요
- 쿼리키를 구조화해서 같은 api call에 대한 다른 쿼리키를 페칭하는 것을 방지 및 쿼키키기반 invalidate 를 구조화
- 구조화된 쿼리키를 이용해 각각의 스키마마다 적절한 캐싱시간 부여

## ✔️ To-Do
- [ ] 투두 내용 작성

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 보통 자신만 write 및 read하는 데이터는 쿼리타임을 무한으로 주긴함
