### ISSUE TITLE
BE: 백엔드 소켓 송신대상 설정

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#498]
## 📝 개요
- userId가 같아도 다른 client id라면 일단 보내도록함
- 여러탭과 디바이스를 위한 기능

## ✔️ To-Do
- [ ] 투두 내용 작성

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
