### ISSUE TITLE
BE: refresh token 관련 문제

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#500]
## 📝 개요
- 리프레시 토큰이 이미 발급 되어있고, 만료 안됐으면 그대로 가져와야 함
- 근데 로그인 시도하면 새로 발급함
- 이미 있으면 그거 가져오게 로직 변경

## ✔️ To-Do
- [ ] auth - generateRefreshToken 함수 수정

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
