### ISSUE TITLE
BE: 세션 목록, 파일 목록 보내줄 때 pagination

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#503]
## 📝 개요
- 쿼리로 page number, limit 보내주면 그거 맞춰서 전달
- 페이지 범위도 같이 전달 (1~5? 4까지밖에 없으면 1~4)

## ✔️ To-Do
- [ ] 페이지네이션 옵션 추가

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
