### ISSUE TITLE
FE: global skeletons

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#510]
## 📝 개요
- 페이지 및 컴포넌트 전체적인 skeleton ui 적용

## ✔️ To-Do
- [X] skeleton ui 구성

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [X] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함
