### ISSUE TITLE
FE: PaintPDF 이벤트 핸들러 아키텍쳐

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#511]
## 📝 개요
- PDF 페이지 전환시 수행할 함수를 주입 가능한 이벤트 핸들러 구조
- prev -> current로 전환시 prev 페이지에 대해 수행할 작업, currentpage에 대해 수행할 작업

## ✔️ To-Do
- [ ] prev 페이지 이벤트 핸들러
- [ ] current 페이지 이벤트 핸들러
- [ ] 이벤트 핸들러 메모리 해제 함수
- [ ] 이벤트 핸들러 관리 체계

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [x] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
```typescript
	listen(onHistory: StoreListener<R>, filters?: Partial<StoreListenerFilters>) {
		// flush history so that this listener's history starts from exactly now
		this._flushHistory()

		const listener = {
			onHistory,
			filters: {
				source: filters?.source ?? 'all',
				scope: filters?.scope ?? 'all',
			},
		}

		this.listeners.add(listener)

		if (!this.historyReactor.scheduler.isActivelyListening) {
			this.historyReactor.start()
		}

		return () => {
			this.listeners.delete(listener)

			if (this.listeners.size === 0) {
				this.historyReactor.stop()
			}
		}
	}

```
