### ISSUE TITLE
FE: 페이지 전환시 이전페이지 데이터 송신

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#513]
## 📝 개요
- 현재 서버에 많은 양의 JSON을 짧은 주기로 보냅니다.
- 이벤트 리스너를 통해 페이지 전환시 JSON을 보냄니다

## ✔️ To-Do
- [ ] 인터벌을 약간 늘립니다. (10초)
- [ ] 페이지 전환시 송신합니다.

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- #512
