### ISSUE TITLE
FE: 클라이언트 필기 데이터 불러오기 관리

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#514]
## 📝 개요
- 현재는 로컬스토리지만 사용합니다.
- 세션 스토리지를 통해 메모리 관리를 편리하게 하고
- 만약에 세션 스토리지에 캐싱돼있지 않다면 서버에불러옴

## ✔️ To-Do
- [ ] 투두 내용 작성

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [x] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 세션스토리지 내용이 stale한지는 현재는 하지 않을 것
- 아마 타임스태프를 추가로 정의해두면 될 것 같긴한데...
#512
