### ISSUE TITLE
FE: 확대 인풋 버튼

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#515]
## 📝 개요
- PDF 문서 하단 왼쪽에 버튼으로 스케일 조정할 수 있는 거

## ✔️ To-Do
- [ ] PDF 문서 하단 왼쪽에 PDF 전환 인풋처럼 만들어보기

## 예상 마감 기한
- [ ] 핫 픽스
- [x] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
