### ISSUE TITLE
FE: 로컬스토리지 필기 저장 방식 개선

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#518]
## 📝 개요
- 현재, 캐치업 프로젝트에 필기를 하면 필기 데이터가 디바이스에 영구적으로 남고 삭제가 안됨
- 세션을 나가면 삭제를 하도록 하거나, 페이지에 들어오면 초기화 시키거나, 대시보드에서 기기데이터 삭제 버튼등을 만들어 삭제하거나
- 세션스토리지 이용해 유저가 나가면 삭제하도록 함
- 로컬스토리지가 더 적합하다하면, 성능이 더 우수한 indexedDB 사용을 고려할 수 있으나, 솔직히 너무 어려움

## ✔️ To-Do
- [ ] 투두 내용 작성

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [x] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- [세션스토리지](https://developer.mozilla.org/ko/docs/Web/API/Window/sessionStorage)
- [로컬스토리지](https://developer.mozilla.org/ko/docs/Web/API/Window/localStorage)
