### ISSUE TITLE
FE: unable to use guest login 

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#525]
## 📝 개요
- 게스트 로그인 기능이 동작하지 않음

## ✔️ To-Do
- [ ] 로그인 버튼 수정

## 예상 마감 기한
- [ ] 핫 픽스
- [X] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
<img width="685" alt="image" src="https://github.com/user-attachments/assets/b4ba562b-391c-4afd-8c01-4998a261ab63">
