### ISSUE TITLE
FE: ignore 401 on logout

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#526]
## 📝 개요
- 로그아웃 페이지에 접근 시 이미 로그아웃이 되어있거나 인증 오류가 발생한다면 무시하고 메인 페이지로 redirect
- 로그아웃이 목적이기 때문에 불필요한 오류를 발생시키지 않도록 개선

## ✔️ To-Do
- [ ] 로그아웃 페이지 개선

## 예상 마감 기한
- [ ] 핫 픽스
- [X] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/ef22913d-e73d-4bdc-bcbc-3d0c8692ff3d">
