### ISSUE TITLE
FE: prevent default event on button click

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#531]
## 📝 개요
- 프로필 이미지 변경 버튼을 누를 경우 form 자체가 전송되어 api가 호출됨.

## ✔️ To-Do
- [ ] 기본 이벤트 방지

## 예상 마감 기한
- [ ] 핫 픽스
- [X] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함
