### ISSUE TITLE
BE: Guest Login 구현

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#533]
## 📝 개요
- 게스트 로그인 구현
- GET /auth/guest 를 통해 로그인
- 프론트의 로컬 id 해쉬값을 사용해 저장
- JWT 생성 후 payload의 isGuest 값이 true 면 guest로 처리
- 만약 소셜로그인으로 회원가입 완료하면, 데이터를 해당 유저로 저장

## ✔️ To-Do
- [ ] jwt payload 변경
- [ ] guest mode 로그인 api 작성
- [ ] 만약 guest jwt가 존재하는데, 소셜 로그인을 할 경우 해당 guest 유저데이터를 실제 데이터로 업데이트

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성

**Comment by nayounsang** [comment]
3번 TODO는 작업량이 많아 분할하는게 좋아보이고, 사실 굳이 필요한가 의문이 듬

**Comment by nayounsang** [comment]
> 3번 TODO는 작업량이 많아 분할하는게 좋아보이고, 사실 굳이 필요한가 의문이 듬

만약 구현하겠다면, 우선순위가 낮은 다른 작업으로
왜냐하면 "게스트로그인을 가능하게 한다" 라는 문제를 해결하는건 1,2번으로 충분해보임

**Comment by 1000chw** [comment]
그럼 일단 1, 2번으로 진행하고, 3번은 시간 날 때 해보는 걸로 갈게
