### ISSUE TITLE
FE: fix session join

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#534]
## 📝 개요
- 세션 접속 페이지에서 세션 코드를 입력할 경우 올바르지 않은 url로 이동됨.

## ✔️ To-Do
- [ ] 세션 접속 페이지에서 세션 미리보기 구현
- [ ] 올바른 세션 url로 이동

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [X] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
