### ISSUE TITLE
FE: fix loading.tsx

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#535]
## 📝 개요
- 앱 내부의 텍스트로만 구현된 loading.tsx 파일들을 skeleton UI로 변환

## ✔️ To-Do
- [ ] 앱 내부의 텍스트로만 구현된 loading.tsx 파일들을 skeleton UI로 변환

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [X] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
