### ISSUE TITLE
FE: 공통 프리티어 설정

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#540]
## 📝 개요
- 지원, 나는 IDE 기본제공 프리티어를 사용중이나, 서로 그 내용이 달라 코드리뷰시 단순 포맷팅 변경과같은 불필요한 것도 변경사항에 저장됨

## ✔️ To-Do
- [ ] 투두 내용 작성

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [x] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [x] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
