### ISSUE TITLE
FE: 뷰어 버그 수정 및 편의성 개선

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#542]
## 📝 개요
- 전반적인 수정
- 모드 변경 기능을 제거하고 단순하게 제어할 수 있도록 구현하는 것이 목표
- 분산된 기능들을 통합하여 안정성과 통일성 제공
- 사용자 경험 향상

## ✔️ To-Do
- [ ] 페이지 확대 및 이동의 영역이 올바르지 않은 문제 수정
- [ ] 키보드가 사용 가능한 환경에서 보기 모드와 이동 모드를 구분하지 않고 Ctrl 등의 키보드 입력으로 바로 전환할 수 있도록 개선 (Mouse Drag: 텍스트 선택, Ctrl + Scroll: 확대/축소, Ctrl + Mouse Drag: 문서 내부 이동)
- [ ] 필기 모드 상태에서의 '마우스 포인터' 도구를 일반 보기 모드로 통합

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [X] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
