### ISSUE TITLE
TOT: 프로젝트 리드미 작성

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#546]
## 📝 개요
- 하 언제하냐 파이팅

## ✔️ To-Do
- [ ] 투두 내용 작성

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [x] 난이도가 있어 추정 불가
- [ ] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
