### ISSUE TITLE
FE: 뷰어 내부 페이지 이동 시 tldraw의 history가 유지되는 문제

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#552]
## 📝 개요
- 뷰어 내부 페이지를 이동하더라도 tldraw의 history가 유지되어 실행취소/실행복원이 올바르게 동작하지 않는 문제

## ✔️ To-Do
- [ ] 페이지 이동 시 tldraw의 history 삭제

## 예상 마감 기한
- [ ] 핫 픽스
- [ ] 오늘
- [ ] 3일
- [ ] 1주일 이상
- [ ] 난이도가 있어 추정 불가
- [X] 우선순위가 낮아 고려 안함

## 👀 ETC
- 참고자료 등 기타 내용 작성
