### ISSUE TITLE
react-query 프로젝트에 적용

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#6]
## 📝 개요
- 서버 상태 관리를 위한 리액트 쿼리 프로젝트에 적용

## ✔️ To-Do
- [ ] 리액트 쿼리 설치
- [ ] 리액트 쿼리 lint 적용
- [ ] 쿼리 프로바이더 적용

## 👀 ETC
- query client default option을 필요하다면 적용해야할 것입니다
