### ISSUE TITLE
BE: 서비스에 필요한 DB 엔티티 생성

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#81]
## 📝 개요
- 각종 엔티티 생성
- 잘 읽어오나 테스트

## ✔️ To-Do
- [x] Sessions 엔티티 생성
- [x] Files 엔티티 생성
- [x] Notes 엔티티 생성
- [x] user, session, file 간 join relation 연결
- [x] DB 에 데모 데이터 넣기
- [x] typeORM으로 데이터 잘 읽어오는지 확인

## 👀 ETC
- 참고자료 등 기타 내용 작성
