### ISSUE TITLE
FE: 사이드바 스윗치 라우팅 가능

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#87]
## 📝 개요
- 사이드바 디자인을 개선하고 스위치 기능추가를 통한 고도화

## ✔️ To-Do
- [ ] 사이드바에 텍스트 컴포넌트 사용
- [ ] 사이드바에 마진 및 패딩 적용
- [ ] 스위치누르면 쿼리파라미터 변환

## 👀 ETC
- 파이팅
