### ISSUE TITLE
BE: /user/sessions RUD api 제작

### ISSUE THREAD

**Issue by 1000chw** [Uni-class/catch-up-repo#99]
## 📝 개요
- /user/sessions GET, POST, PATCH, DELETE 제작

## ✔️ To-Do
- [ ] GET /user/sessions
- [ ] POST /user/sessions
- [ ] PATCH /user/sessions
- [ ] DELETE /user/sessions

## 👀 ETC
- 참고자료 등 기타 내용 작성
